DROP TABLE IF EXISTS [FlyWithButchOhareDB_Copy].[dbo].[wordflightwords];
DROP TABLE IF EXISTS [FlyWithButchOhareDB_Copy].[dbo].[wordflightleaderboard];
DROP TABLE IF EXISTS [FlyWithButchOhareDB_Copy].[dbo].[wordflightsponsors];

CREATE TABLE [FlyWithButchOhareDB_Copy].[dbo].[WordFlightLeaderboard]
(
	[entry_id] INT NOT NULL PRIMARY KEY IDENTITY (1, 1), 
    [user] CHAR(2) NOT NULL, 
    [score] INT NOT NULL
);

CREATE TABLE [FlyWithButchOhareDB_Copy].[dbo].[WordFlightSponsors]
(
	[sponsor_id] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	[sponsor_name] VARCHAR(28) NOT NULL
);

CREATE TABLE [FlyWithButchOhareDB_Copy].[dbo].[WordFlightWords]
(
	[word_id] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	[sponsor_id] INT NOT NULL,
	[word] VARCHAR(15) NOT NULL,
	CONSTRAINT FK_WordFlightWords_WordFlightSponsors
		FOREIGN KEY (sponsor_id)
		REFERENCES WordFlightSponsors (sponsor_id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

INSERT INTO [FlyWithButchOhareDB_Copy].[dbo].[wordFlightSponsors] ([sponsor_name]) VALUES
('Argo Tea'),
('Auntie Annes'),
('Brookstone'),
('BSmooth'),
('Burrito Beach'),
('Chicago Sports'),
('CNN'),
('Coach'),
('Dunkin Donuts'),
('Duty Free Store'),
('Field'),
('Hudson'),
('Mac Cosmetics'),
('Nuts on Clark'),
('Rocky Mountain Chocolate'),
('Sarahs Candies'),
('Shoe Hospital'),
('Spirit of the Red Horse'),
('Talie');

INSERT INTO [FlyWithButchOhareDB_Copy].[dbo].[wordflightleaderboard] ([user], [score]) VALUES
('AB', 1000),
('BC', 500),
('CD', 250),
('DE', 125),
('EF', 100),
('FG', 75),
('GH', 50),
('HI', 40),
('IJ', 30),
('JK', 20),
('KL', 10);

INSERT INTO [FlyWithButchOhareDB_Copy].[dbo].[wordflightwords] ([sponsor_id], [word]) VALUES
(1, 'chai'),
(1, 'cider'),
(1, 'latte'),
(1, 'blacktea'),
(1, 'hot chocolate'),
(1, 'earl grey'),
(1, 'white tea'),
(1, 'coffee'),
(1, 'ginger peach'),
(1, 'barista'),
(2, 'pretzel'),
(2, 'cinnamon sugar'),
(2, 'lemonade'),
(2, 'soda'),
(2, 'cheese dip'),
(2, 'sweet almond'),
(2, 'pepperoni'),
(2, 'mini dogs'),
(2, 'cherry'),
(2, 'blue raspberry'),
(3, 'globe'),
(3, 'sandbox'),
(3, 'RC vehicle'),
(3, 'bean bag game'),
(3, 'cloud sand'),
(3, 'photo frame'),
(3, 'mini fan'),
(3, 'wallet'),
(3, 'organizer'),
(3, 'sound mixer'),
(4, 'strawberry'),
(4, 'banana'),
(4, 'blueberry'),
(4, 'pineapple'),
(4, 'frozen yogurt'),
(4, 'garbanzo beans'),
(4, 'salad'),
(4, 'edamame'),
(4, 'fresh spinach'),
(5, 'quesadillas'),
(5, 'tacos'),
(5, 'burritos'),
(5, 'shrimp'),
(5, 'homemade salsa'),
(5, 'goat cheese'),
(5, 'eggs'),
(5, 'chips'),
(5, 'steak'),
(6, 'bulls'),
(6, 'blackhawks'),
(6, 'bears'),
(6, 'whitesox'),
(6, 'cubs'),
(6, 'cap'),
(6, 'jacket'),
(6, 't-shirt'),
(6, 'hoodie'),
(6, 'sweatshirt'),
(7, 'news stand'),
(7, 'trail mix'),
(7, 'books'),
(7, 'snacks'),
(7, 'convenience'),
(7, 'drinks'),
(7, 'magazines'),
(7, 'candy'),
(7, 'gum'),
(7, 'bars'),
(8, 'purse'),
(8, 'fashion'),
(8, 'coats'),
(8, 'handbag'),
(8, 'tote'),
(8, 'carryalls'),
(8, 'satchels'),
(8, 'clutch'),
(8, 'backpack'),
(8, 'shoulder bag'),
(9, 'iced coffee'),
(9, 'hot coffee'),
(9, 'donut'),
(9, 'munchkin'),
(9, 'muffin'),
(9, 'bagel'),
(9, 'croissant'),
(9, 'juice'),
(9, 'wrap'),
(9, 'sandwich'),
(10, 'pens'),
(10, 'ornament'),
(10, 'sunglasses'),
(10, 'luggage'),
(10, 'necklaces'),
(10, 'silver'),
(10, 'gold'),
(10, 'ring'),
(10, 'bracelet'),
(10, 'earrings'),
(11, 'dinosaurs'),
(11, 'lollipop'),
(11, 'mood ring'),
(11, 'tie-dye'),
(11, 'playing cards'),
(11, 'explorer hat'),
(11, 'puzzles'),
(11, 'game'),
(11, 'kits'),
(11, 'machines'),
(12, 'media'),
(12, 'bookstore'),
(12, 'tabloids'),
(12, 'mints'),
(12, 'marketplace'),
(12, 'crackers'),
(12, 'mugs'),
(12, 'bear plush'),
(12, 'water bottle'),
(12, 'wipes'),
(13, 'eye shadow'),
(13, 'makeup'),
(13, 'lipstick'),
(13, 'blush'),
(13, 'foundation'),
(13, 'mascara'),
(13, 'lip gloss'),
(13, 'powder'),
(13, 'brushes'),
(13, 'lotion'),
(14, 'popcorn'),
(14, 'caramel corn'),
(14, 'cheese corn'),
(14, 'kettle corn'),
(14, 'treats'),
(14, 'snack mix'),
(14, 'beverages'),
(14, 'milk chocolate'),
(14, 'dark chocolate'),
(14, 'cranberry mix'),
(15, 'caramel apples'),
(15, 'fudge'),
(15, 'dipped oreos'),
(15, 'toffees'),
(15, 'truffles'),
(15, 'creams'),
(15, 'barks'),
(15, 'sugar free'),
(15, 'cookie dough'),
(16, 'delicious'),
(16, 'assorted nuts'),
(16, 'cashews'),
(16, 'almonds'),
(16, 'smores cluster'),
(16, 'delights'),
(16, 'chocolatier'),
(16, 'local'),
(16, 'cookbook'),
(16, 'sweetness'),
(17, 'shine'),
(17, 'polish'),
(17, 'laces'),
(17, 'insoles'),
(17, 'socks'),
(17, 'buff'),
(17, 'shoe shapers'),
(17, 'comfort'),
(17, 'soles'),
(17, 'replacements'),
(18, 'jewelry'),
(18, 'beautiful'),
(18, 'home accents'),
(18, 'eagle'),
(18, 'pottery'),
(18, 'elk'),
(18, 'leather'),
(18, 'dreamcatcher'),
(18, 'pueblo drums'),
(19, 'gifts'),
(19, 'design'),
(19, 'scarves'),
(19, 'glass earrings'),
(19, 'unique'),
(19, 'ponchos'),
(19, 'blouses'),
(19, 'shawls'),
(19, 'shades');